# Generated by Django 5.2.5 on 2025-08-29 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('cpu_cores', models.IntegerField()),
                ('cpu_frequency', models.FloatField(help_text='GHz')),
                ('gpu_model', models.CharField(blank=True, max_length=100)),
                ('gpu_memory', models.IntegerField(blank=True, help_text='GB', null=True)),
                ('ram', models.IntegerField(help_text='GB')),
                ('storage', models.IntegerField(help_text='GB')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('restarting', 'Restarting')], default='offline', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start', 'Start'), ('stop', 'Stop'), ('restart', 'Restart'), ('maintenance', 'Maintenance')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='servers.server')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
